displayName: RAPP Agent
schemaName: crf9a_agent2_L4Y3ee
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - channelId: MsTeams

  gPTSettings:
    defaultSchemaName: crf9a_agent2_L4Y3ee.gpt.default

  isLightweightBot: false
  aISettings:
    useModelKnowledge: true
    isSemanticSearchEnabled: true
    isFileAnalysisEnabled: true
    contentModeration: Medium
    optInUseLatestModels: true
    generativeAnswersEnabled: true
    boostedConversationsEnabled: true
  settings:
    orchestrationType: Generative

  analyticsSettings:
    roiCalculation:
      kind: SessionBasedRoiCalculationSettings
      currencyCode: USD
      savedCost: 149
      savedTimeInSeconds: 600

publishedOn: 2026-01-22T13:57:27.0000000Z
template: default-2.1.0
language: 1033