"""
Agent: MfgCoE Outcome Framer Agent
Purpose: Runs FIRST on every issue before any build work starts.
         Defines the business problem, affected users, success KPI, and acceptance
         criteria. Inspired by CongruentX outcome-based delivery — nothing moves to
         tech-solution until the outcome is clearly defined and traceable.

Actions:
  frame_outcome     — Define business problem, affected users, KPI, and acceptance criteria
  review_outcome    — Review an existing outcome definition for completeness
  backfill_outcome  — Add outcome definition to an existing issue that lacks one
  list_outcomes     — List all outcome definitions logged
"""

import json
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

from agents.basic_agent import BasicAgent
from customers.mfg_coe.agents.context_card_loader import load_context_card

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

OUTCOMES_DIR = os.path.normpath(
    os.path.join(os.path.dirname(__file__), "..", "outcomes")
)

# Outcome KPI library — maps process areas to common measurable metrics
KPI_LIBRARY = {
    "warranty": [
        "Warranty resolution rate (% resolved without escalation)",
        "Customer handle time for warranty inquiry (minutes)",
        "Self-service containment rate (%)",
        "CSAT score post-warranty interaction",
    ],
    "case_management": [
        "First contact resolution rate (%)",
        "Average case handle time (minutes)",
        "Escalation rate (%)",
        "Agent utilization rate (%)",
    ],
    "field_service": [
        "Mean time to resolve (MTTR) in hours",
        "First-time fix rate (%)",
        "Technician dispatch time (hours)",
        "Parts availability at time of dispatch (%)",
    ],
    "returns_rma": [
        "RMA processing time (days)",
        "Cost per return ($)",
        "Return rate (%)",
        "Customer effort score for returns",
    ],
    "dealer_management": [
        "Deal registration rate (%)",
        "Partner portal adoption rate (%)",
        "Time-to-quote for channel partners (hours)",
        "Partner satisfaction score (NPS)",
    ],
    "crm": [
        "Lead-to-order cycle time (days)",
        "Sales rep productivity (opportunities per rep)",
        "CRM data completeness (%)",
        "Forecast accuracy (%)",
    ],
    "order_management": [
        "Order processing time (hours)",
        "Order error rate (%)",
        "On-time delivery rate (%)",
        "Order status self-service rate (%)",
    ],
    "default": [
        "Process completion time reduction (%)",
        "User effort score (1-5)",
        "Error/exception rate (%)",
        "Adoption rate among target users (%)",
    ],
}

OUTCOME_TEMPLATE = """# Outcome Definition: {title}

**Issue:** #{issue_number}
**Date Framed:** {date}
**Framed By:** Outcome Framer Agent
**Status:** Draft — awaiting Bill's review

---

## Business Problem

{business_problem}

## Who Is Affected

**Primary Users:** {primary_users}
**Secondary Stakeholders:** {secondary_stakeholders}
**Current Pain:** {current_pain}

## Before State (Today)

{before_state}

## After State (With Solution)

{after_state}

## Success KPIs

{kpis}

## Acceptance Criteria

{acceptance_criteria}

## Scope Boundaries

**In scope:**
{in_scope}

**Out of scope:**
{out_of_scope}

## Demo Story (One Sentence)

{demo_story}

---

*Generated by MfgCoE Outcome Framer | {date}*
*This definition must be confirmed before any build work begins.*
"""


# Outcome confidence signals — high-signal words that indicate someone
# has already thought about the business outcome, not just the technology.
OUTCOME_KEYWORDS = [
    "reduce", "improve", "faster", "less time", "save time", "eliminate",
    "increase", "decrease", "automate", "self-service", "without calling",
    "customer can", "rep can", "% reduction", "% improvement", "hours to",
    "days to", "minutes to", "cost per", "rate", "score", "nps", "csat",
    "first contact", "handle time", "resolution", "escalation", "kpi",
    "outcome", "success looks like", "we want", "goal is", "target is",
    "measure", "metric", "baseline", "benchmark", "roi",
]

BLOCKING_QUESTIONS = [
    "**What business problem does this solve for the end user?** (not the technology — what frustration, delay, or error is this fixing?)",
    "**Who specifically is affected today?** Describe their current day without this solution.",
    "**How will we measure success?** What number gets better, by how much, within what timeframe?",
    "**What does a winning 60-second demo look like?** What does the customer see that makes them say 'yes'?",
]


def _score_outcome_confidence(issue_title: str, issue_body: str) -> dict:
    """Score how much outcome context exists. Returns score (0-100) and confidence level."""
    body = (issue_body or "").lower()
    title = (issue_title or "").lower()
    combined = title + " " + body

    score = 0

    # Base signal: has a real description
    body_len = len(body.strip())
    if body_len > 300:
        score += 25
    elif body_len > 100:
        score += 15
    elif body_len > 20:
        score += 5

    # High-signal outcome keywords present
    hits = [kw for kw in OUTCOME_KEYWORDS if kw in combined]
    score += min(35, len(hits) * 7)

    # Customer name present → context available
    if any(c.lower() in combined for c in ["navico", "otis", "zurn", "vermeer", "carrier", "aes"]):
        score += 10

    # Specific numbers or percentages → quantified thinking
    import re
    if re.search(r'\d+\s*%|\$\d+|\d+\s*hour|\d+\s*day|\d+\s*minute', combined):
        score += 20

    # Explicit "outcome" or "goal" language → they thought about it
    if any(phrase in combined for phrase in ["outcome", "goal is", "success looks like", "kpi", "measure"]):
        score += 10

    # Penalty: body is basically just a URL (no real description)
    if body_len < 50 or body.strip().startswith("http"):
        score = min(score, 20)

    score = min(100, score)

    if score >= 60:
        level = "high"
    elif score >= 35:
        level = "medium"
    else:
        level = "low"

    return {"score": score, "level": level, "keyword_hits": hits}


class MfgCoEOutcomeFramerAgent(BasicAgent):
    """
    Outcome Framer — runs first on every CoE issue.
    Defines business problem, affected users, measurable KPIs, and acceptance criteria
    before any technical work starts. Nothing moves to tech-solution without this.

    If the issue body lacks sufficient outcome context (confidence < 35), the pipeline
    is BLOCKED — a specific set of questions is posted to the issue with a needs-bill
    label so Bill can provide the missing outcome definition before any build work starts.
    Outcomes are the MVP. No outcome definition = no build.
    """

    def __init__(self):
        self.name = "MfgCoEOutcomeFramer"
        self.metadata = {
            "name": self.name,
            "description": (
                "Outcome Framer agent — runs BEFORE any build work on CoE issues. "
                "Defines the business problem, affected users, success KPIs, and "
                "acceptance criteria. Inspired by CongruentX outcome-based delivery. "
                "Use this agent at the start of every issue to ensure we're solving "
                "the right problem for the right business user with measurable success criteria."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "action": {
                        "type": "string",
                        "enum": [
                            "frame_outcome",
                            "review_outcome",
                            "backfill_outcome",
                            "list_outcomes",
                            "request_outcome",
                        ],
                        "description": "Outcome framing action to perform",
                    },
                    "issue_number": {
                        "type": "integer",
                        "description": "GitHub issue number to frame outcome for",
                    },
                    "issue_title": {
                        "type": "string",
                        "description": "Title of the GitHub issue",
                    },
                    "issue_body": {
                        "type": "string",
                        "description": "Full body of the GitHub issue",
                    },
                    "process_area": {
                        "type": "string",
                        "enum": [
                            "warranty", "case_management", "field_service",
                            "returns_rma", "dealer_management", "crm",
                            "order_management", "default",
                        ],
                        "description": "Business process area for KPI lookup",
                    },
                    "customer": {
                        "type": "string",
                        "description": "Customer name (Navico, Otis, Zurn, Vermeer, Carrier, AES)",
                    },
                    "outcome_filename": {
                        "type": "string",
                        "description": "Filename of existing outcome definition to review",
                    },
                },
                "required": ["action"],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs) -> str:
        action = kwargs.get("action", "list_outcomes")
        handlers = {
            "frame_outcome": self._frame_outcome,
            "review_outcome": self._review_outcome,
            "backfill_outcome": self._frame_outcome,  # same logic, different label
            "list_outcomes": self._list_outcomes,
            "request_outcome": self._request_outcome,
        }
        handler = handlers.get(action)
        if not handler:
            return json.dumps({"error": f"Unknown action: {action}"})
        try:
            return handler(**kwargs)
        except Exception as e:
            logger.error("OutcomeFramer error in %s: %s", action, e)
            return json.dumps({"error": str(e)})

    def _frame_outcome(self, **kwargs) -> str:
        issue_number = kwargs.get("issue_number", 0)
        issue_title = kwargs.get("issue_title", "Untitled Issue")
        issue_body = kwargs.get("issue_body", "")
        process_area = kwargs.get("process_area", "default")
        customer = kwargs.get("customer", "Discrete Manufacturing customer")

        # Confidence check — if there's not enough outcome context, block the pipeline
        confidence = _score_outcome_confidence(issue_title, issue_body)
        if confidence["level"] == "low":
            return self._request_outcome(
                issue_number=issue_number,
                issue_title=issue_title,
                confidence=confidence,
            )

        # Load environment context
        env_context = ""
        try:
            env_context = load_context_card("master_ce_mfg")
        except Exception:
            pass

        kpis = KPI_LIBRARY.get(process_area, KPI_LIBRARY["default"])
        kpi_md = "\n".join(f"- [ ] **{kpi}** — baseline TBD, target TBD" for kpi in kpis)

        # Derive structured outcome from issue content
        area_display = process_area.replace("_", " ").title()

        business_problem = (
            f"Based on issue: *{issue_title}*\n\n"
            f"{issue_body[:500] if issue_body else '[Extracted from issue — agent to elaborate]'}"
        )

        before_state = (
            f"**Current situation for {customer}:**\n"
            f"- Business users in the {area_display} process rely on manual steps, "
            f"email-based communication, or disconnected systems\n"
            f"- No single view of status available to customer or internal team\n"
            f"- Resolution requires multiple touchpoints and handoffs\n"
            f"- [Agent: refine this with specific details from issue body]"
        )

        after_state = (
            f"**With the solution in place:**\n"
            f"- Business users can self-serve or receive AI-assisted resolution for common {area_display} scenarios\n"
            f"- Single connected flow from intake to resolution via D365 + Copilot Studio\n"
            f"- Measurable reduction in handle time, escalations, and manual effort\n"
            f"- Demo story is complete: customer sees their problem solved, not a feature showcase"
        )

        acceptance_criteria = (
            "- [ ] The demo runs end-to-end without manual intervention\n"
            "- [ ] The business user's problem is visibly solved in the demo flow\n"
            "- [ ] At least one KPI improvement is quantifiable from the demo story\n"
            "- [ ] A customer watching the demo could immediately see *their* process reflected\n"
            "- [ ] Bill can present this to a customer without needing to explain the technology first"
        )

        in_scope = (
            f"- Core {area_display} flow (primary happy path)\n"
            f"- Integration with {customer} demo data in Master CE Mfg\n"
            f"- Copilot Studio + D365 CE end-to-end story"
        )

        out_of_scope = (
            "- ERP / back-office system integrations (Phase 2)\n"
            "- Multi-language / accessibility requirements\n"
            "- Production deployment to customer tenant"
        )

        demo_story = (
            f"A {customer} customer contacts support about a {area_display.lower()} issue, "
            f"receives instant AI-powered resolution or clear next steps — "
            f"no hold times, no manual lookups, no dead ends."
        )

        content = OUTCOME_TEMPLATE.format(
            title=issue_title,
            issue_number=issue_number,
            date=datetime.utcnow().strftime("%Y-%m-%d"),
            business_problem=business_problem,
            primary_users=f"{customer} customer-facing staff and end customers",
            secondary_stakeholders="Service managers, IT admin, demo audience (prospects)",
            current_pain=f"Manual, fragmented {area_display.lower()} process with no AI assistance",
            before_state=before_state,
            after_state=after_state,
            kpis=kpi_md,
            acceptance_criteria=acceptance_criteria,
            in_scope=in_scope,
            out_of_scope=out_of_scope,
            demo_story=demo_story,
        )

        # Save to outcomes dir
        os.makedirs(OUTCOMES_DIR, exist_ok=True)
        safe_title = issue_title.lower().replace(" ", "_")[:40].strip("_")
        filename = f"outcome_{issue_number}_{safe_title}.md"
        filepath = os.path.join(OUTCOMES_DIR, filename)
        Path(filepath).write_text(content, encoding="utf-8")
        logger.info("Outcome definition saved: %s", filepath)

        comment_body = (
            f"## 🎯 Outcome Definition — Issue #{issue_number}\n\n"
            f"**Confidence Level:** {confidence['level'].upper()} ({confidence['score']}/100)\n\n"
            f"**Business Problem:** {issue_title}\n\n"
            f"**Affected Users:** {customer} customer-facing staff and end customers\n\n"
            f"**Before State:** Manual, fragmented {area_display.lower()} process\n\n"
            f"**After State:** AI-assisted, connected flow from intake to resolution\n\n"
            f"**Success KPIs:**\n{kpi_md}\n\n"
            f"**Demo Story:** {demo_story}\n\n"
            f"**Acceptance Criteria:**\n{acceptance_criteria}\n\n"
            f"---\n"
            f"📄 Full outcome definition saved to: `customers/mfg_coe/outcomes/{filename}`\n\n"
            f"**⚠️ Build work should not start until Bill confirms this outcome definition is correct.**\n\n"
            f"_Agent: Outcome Framer | {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC_"
        )

        return json.dumps({
            "status": "outcome_defined",
            "summary": f"Outcome definition created for issue #{issue_number}: {issue_title}",
            "filename": filename,
            "comment_body": comment_body,
            "persona": "outcome-framer",
            "process_area": process_area,
            "kpis": kpis,
            "demo_story": demo_story,
            "confidence": confidence,
        })

    def _request_outcome(self, **kwargs) -> str:
        """Pipeline blocker — called when confidence is too low to proceed."""
        issue_number = kwargs.get("issue_number", 0)
        issue_title = kwargs.get("issue_title", "Untitled Issue")
        confidence = kwargs.get("confidence") or _score_outcome_confidence(issue_title, kwargs.get("issue_body", ""))

        questions_md = "\n\n".join(f"{i+1}. {q}" for i, q in enumerate(BLOCKING_QUESTIONS))

        comment_body = (
            f"## ⛔ Outcome Definition Required — Pipeline Blocked\n\n"
            f"**Issue:** {issue_title} (#{issue_number})\n"
            f"**Confidence Score:** {confidence['score']}/100 ({confidence['level'].upper()})\n\n"
            f"---\n\n"
            f"**The pipeline cannot advance until the business outcome is defined.**\n\n"
            f"Outcomes are the MVP of every use case. We don't build technology for its own sake — "
            f"we deliver verified outcomes that business users can measure and feel.\n\n"
            f"### 🙋 Bill — please answer these questions to unblock this issue:\n\n"
            f"{questions_md}\n\n"
            f"---\n"
            f"> Once you've answered, the Outcome Framer will rerun and the pipeline will resume.\n\n"
            f"_Agent: Outcome Framer | {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC_"
        )

        return json.dumps({
            "status": "outcome_blocked",
            "pipeline_blocked": True,
            "summary": (
                f"Pipeline BLOCKED for #{issue_number} — insufficient outcome context "
                f"(confidence: {confidence['score']}/100). "
                f"Posted {len(BLOCKING_QUESTIONS)} questions. Awaiting Bill's input."
            ),
            "comment_body": comment_body,
            "blocking_questions": BLOCKING_QUESTIONS,
            "confidence": confidence,
            "persona": "outcome-framer",
            "next_steps": [
                "Bill to answer the 4 blocking questions on the issue",
                "Re-run process_issue after Bill responds",
                "Outcome Framer will re-score and proceed if confidence ≥ 35",
            ],
        })

    def _review_outcome(self, **kwargs) -> str:
        outcome_filename = kwargs.get("outcome_filename", "")
        if not outcome_filename:
            return json.dumps({"error": "outcome_filename required for review_outcome"})

        filepath = os.path.join(OUTCOMES_DIR, outcome_filename)
        if not os.path.exists(filepath):
            return json.dumps({"error": f"Outcome file not found: {outcome_filename}"})

        content = Path(filepath).read_text(encoding="utf-8")

        # Check completeness
        required_sections = [
            "Business Problem", "Who Is Affected", "Before State",
            "After State", "Success KPIs", "Acceptance Criteria", "Demo Story"
        ]
        missing = [s for s in required_sections if s not in content]
        kpi_defined = "baseline TBD" not in content
        demo_story_specific = len([l for l in content.split("\n") if "Demo Story" in l and len(l) > 30]) > 0

        score = 100 - (len(missing) * 10) - (20 if not kpi_defined else 0)
        status = "complete" if score >= 80 else "needs_refinement"

        return json.dumps({
            "status": status,
            "score": score,
            "missing_sections": missing,
            "kpi_baselines_set": kpi_defined,
            "demo_story_specific": demo_story_specific,
            "recommendation": (
                "Outcome definition is complete and build work can proceed."
                if status == "complete"
                else f"Outcome definition needs refinement. Missing: {', '.join(missing)}. Set KPI baselines before building."
            ),
            "summary": f"Outcome review complete. Score: {score}/100. Status: {status}.",
            "persona": "outcome-framer",
        })

    def _list_outcomes(self, **kwargs) -> str:
        os.makedirs(OUTCOMES_DIR, exist_ok=True)
        files = sorted(Path(OUTCOMES_DIR).glob("outcome_*.md"))
        if not files:
            return json.dumps({
                "status": "ok",
                "count": 0,
                "outcomes": [],
                "summary": "No outcome definitions found yet. Run frame_outcome to create the first one.",
            })

        outcomes = []
        for f in files:
            lines = f.read_text(encoding="utf-8").split("\n")
            title_line = next((l for l in lines if l.startswith("# Outcome Definition:")), f.name)
            title = title_line.replace("# Outcome Definition:", "").strip()
            status_line = next((l for l in lines if "Status:" in l), "")
            outcomes.append({"file": f.name, "title": title, "status": status_line.strip()})

        return json.dumps({
            "status": "ok",
            "count": len(outcomes),
            "outcomes": outcomes,
            "summary": f"{len(outcomes)} outcome definition(s) on file.",
            "persona": "outcome-framer",
        })
